### ISSUE TITLE
Quickstart is hard to find.

### ISSUE THREAD

**Issue by wallclimber21** [jandecaluwe/urubu#34]
A minor documentation comment: it took a lot of back-and-forth to find the Urubu Quickstart link. (Including typing 'urubu -h' to see if there was an empty project generator the way it is for rails etc.) The only reference being an link buried at the bottom of the 'Installation' page.

Most open source projects dedicate a full Quickstart chapter in their documentation. That's not necessarily the right way of doing it, but it's probably not a bad idea to make Quickstart a bit more visible?

Thanks for listening!

**Comment by alex7217** [comment]
@jandecaluwe are you open to pull requests on this project? I have some experience wriitng technical documentation and would like to help with this project.

:hand: If so, I volunteer to start here with implementing suggestion by @wallclimber21

**Comment by jandecaluwe** [comment]
As I understood @wallclimber21, the issue is not so much the Quickstart documentation, but finding the website. I agree with that and I have now added the link prominently in the navigation.

I find documentation very important and in fact I believe that the Urubu docs are often better than what can be found in similar projects. But I am of course open to all suggestions and improvements, including via pull requests. But I would suggest to discuss suggestions first to make sure we are on the same line.

**Comment by alex7217** [comment]
Agreed! Urubu has great documentation to match its great functionality! Happy new year and thank you for providing this great project.

**Comment by wallclimber21** [comment]
Look good!
