### ISSUE TITLE
YAML date: time value not accepted

### ISSUE THREAD

**Issue by kristofvanlandschoot** [jandecaluwe/urubu#36]
It would be great to be able to have a date-field like this:
  2011-10-08T17:06:47+02:00,
or even in a string like this:
  '2011-10-08T17:06:47+02:00'

but urubu only accepts 2011-10-08. This can be problematic if you have two posts on the same day.

**Comment by jandecaluwe** [comment]
Mm, I admit I didn't consider the possibility of more than one useful post a day ;-)

I'll accept a pull request if this is done jekyll-style - optional time.

**Comment by twinshadow** [comment]
I've been using the ISO8601 date-time format (without timezone) in the front-matter without any issues. The change needed to display the time differently is in `_Python/filters.py` in the project folder.

I would find it useful to see the error (display or otherwise) that needs fixing here. For reference, I'm currently using the following front-matter on the site I'm developing. Changing the hours and minutes, or adding a timezone, I have observed affecting the ordering on the generated index.html page using a project based on `urubu-quickstart`.

```
---
layout: page
date: 2016-05-05T22:24:04
---
```
