### ISSUE TITLE
Markdown parser issue

### ISSUE THREAD

**Issue by kristofvanlandschoot** [jandecaluwe/urubu#38]
Every markdown parser I know renders this fine:

> ---------------------------
> Here is a list.
> 
> * **Title 1**
> 
>   Indented content 1
> 
> * **Title 2**
> 
>   Indented content 2
---------------------------

except for the one in urubu (which I believe is the standard python one?), where the indented content is not indented at all.

(the editor here on github seems to parse this as well, so to be clear, this is a gist with the problematic markdown: https://gist.github.com/kristofvanlandschoot/ed5d0eb33c721ddade78 )

I guess in the long run commonmark is the way to go, so compliance with commonmark would be great. Commonmark renders this correctly.

**Comment by jandecaluwe** [comment]
I used python-markdown because it seemed to be the most mature one with the best documentation.

If you think this is a bug, I suggest to raise an issue with them. I did that recently, and got a swift response.

I would assume they will comply with commonmark over time, but I have no idea about status.

I will consider other parsers, but they should have a good and well documented API - the ProjectReference extension that resolves Markdown reference links over the project is fundamental in Urubu.

**Comment by jandecaluwe** [comment]
Update: I have reviewed this. According to the original Markdown spec, continuation paragraphs in lists should be indented with 4 spaces, and that is what python-markdown supports. So it looks like it is more compliant with the original spec than other parsers you refer to.

**Comment by kristofvanlandschoot** [comment]
Fair enough, seems to work.
