### ISSUE TITLE
Is it possible to create extensionless urls?

### ISSUE THREAD

**Issue by saulpw** [jandecaluwe/urubu#64]
How would I create a page at domain.com/faq, for example?  Ideally I could configure Urubu such that faq.md becomes faq/index.html, but setting file_ext to "/index.html" breaks the root index.md.  And creating a 'faq/index.md' doesn't work because index pages are special and apparently can't just have straight content.  So is there any way to create these clean urls?

**Comment by leouieda** [comment]
@saulpw my guess is that the easiest way is to create a `faq/index.md` file. Urubu maps the md file structure into HTML and that's actually one of it's strengths. You don't have to guess what generated a certain HTML file.

**Comment by saulpw** [comment]
@leouieda Yeah, I tried that, and it doesn't work unfortunately, I guess because index.md are special:

`urubu.UrubuError: in faq/index.md: No 'content' or 'order' specified`

**Comment by leouieda** [comment]
@saulpw they are special because they need to know in what order the content inside the folder is organized. You can specify `content:` as an ordered list of entries or use `order: date` to organize whatever is in there by date. If you have no content expect the `index.md` file, specifying `order: date` in the header should solve your problem.

**Comment by saulpw** [comment]
Okay, thank you!  Specifying `order: date` worked as you said.

**Comment by leouieda** [comment]
👍
